/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogo;

import javax.swing.JOptionPane;

/**
 *
 * @author Fabricio
 */
public class jogo extends javax.swing.JFrame {
        
        String aux="";
        
        String[] test=new String[15];
        
      
        
        
    /**
     * Creates new form jogo
     */
    public jogo() {
        initComponents();
        
        
                   
        test[0]=bt1.getText();
        test[1]=bt2.getText();
        test[2]=bt3.getText();
        test[3]=bt4.getText();
        test[4]=bt5.getText();
        test[5]=bt6.getText();
        test[6]=bt7.getText();
        test[7]=bt8.getText();
        test[8]=bt9.getText();
        test[9]=bt10.getText();
        test[10]=bt11.getText();
        test[11]=bt12.getText();
        test[12]=bt13.getText();
        test[13]=bt14.getText();
        test[14]=bt15.getText();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt15 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt13 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt16 = new javax.swing.JButton();
        bt14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt15.setText("15");
        bt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt15ActionPerformed(evt);
            }
        });

        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt10.setText("10");
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });

        bt11.setText("11");
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });

        bt12.setText("12");
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });

        bt13.setText("13");
        bt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt13ActionPerformed(evt);
            }
        });

        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt16.setText("2");
        bt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt16ActionPerformed(evt);
            }
        });

        bt14.setText("14");
        bt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(bt16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bt16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
            // TODO add your handling code here:
            
     if((!(bt1.getText().equals("")))&&(bt2.getText().equals("")||bt6.getText().equals(""))){
         int cont=0;
         int verifica=0;  
         
                aux=bt1.getText();
                bt1.setText("");
                test[0]="";
                if(bt2.getText().equals("")){
                      
                      bt2.setText(aux);
                      test[1]=aux;
                      
                      
                }else if(bt6.getText().equals("")){
                    
                    bt6.setText(aux);
                    test[5]=aux;
                }
                
            
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
              
             
            
                
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            
            
            
          
       }       //
            
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt16ActionPerformed
        // TODO add your handling code here:
       
        //teste lógico que verifica se algum dos blocos que estão ao redor, que podem interagir com esse botão, está vazio.
       if(bt16.getText().equals("")||bt11.getText().equals("")||bt12.getText().equals("")||bt13.getText().equals("")||bt14.getText().equals("")||bt15.getText().equals("")){
           //se chave for false, significa que esse é o primeiro botão que o usuário interagio no turno atual 
           if(chave==false&&!(bt16.getText().equals(""))){
                aux=bt16.getText();
                chave=true; 
              //se chave for verdadeiro, significa que esse é o segundo botão que o usuário interagio no turno atual.  
            }else if (chave==true){
                bt16.setText(aux);
                 chave=false;
               //após fazer a atribuição no botão atual, o próximo teste tem a responsabilidade de atualizar o botão anterior com o "".
                 if(bt11.getText().equals(aux)){
                      
                     bt11.setText("");
                     test[10]="";
                     
                }else if(bt12.getText().equals(aux)){
                    
                    bt12.setText("");
                    test[11]="";
                    
                }else if(bt13.getText().equals(aux)){
                     
                    bt13.setText("");
                    test[12]="";
                    
                }else if(bt14.getText().equals(aux)){
                    
                    bt14.setText("");
                    test[13]="";
                    
                }else if(bt15.getText().equals(aux)){
                     
                    bt15.setText("");
                    test[14]="";
                    
                }
                 
               
            }
          
       }
        
    }//GEN-LAST:event_bt16ActionPerformed

    private void bt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt13ActionPerformed
        // TODO add your handling code here:
        if(bt8.getText().equals("")||bt12.getText().equals("")||bt13.getText().equals("")||bt14.getText().equals("")||bt16.getText().equals("")){
            if(chave==false&&!(bt13.getText().equals(""))){
                aux=bt13.getText();
                chave=true;
             }else if(chave==true){
                bt13.setText(aux);
                 chave=false;
                 test[12]=aux;
                if(bt12.getText().equals(aux)){
                      
                      bt12.setText("");
                      test[11]="";
                      
                }else if(bt8.getText().equals(aux)){
                    
                    bt8.setText("");
                    test[7]="";
                }else if(bt16.getText().equals(aux)){
                     
                    bt16.setText("");
                    
                }else if(bt14.getText().equals(aux)){
                    
                    bt14.setText("");
                    test[13]="";
                }
                
                int cont=0;
                int verifica=0;
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                           
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
               if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            }
            
            
          
       }       // TODO 
    
    }//GEN-LAST:event_bt13ActionPerformed

    private void bt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt15ActionPerformed
    
     if(bt15.getText().equals("")||bt14.getText().equals("")||bt16.getText().equals("")||bt10.getText().equals("")){
            if(chave==false&&!(bt15.getText().equals(""))){
                aux=bt15.getText();
                chave=true;
             }else if(chave==true){
                bt15.setText(aux);
                test[14]=aux;
                 chave=false;
                if(bt10.getText().equals(aux)){
                      
                      bt10.setText("");
                      test[9]="";
                      
                }else if(bt14.getText().equals(aux)){
                    
                    bt14.setText("");
                    test[13]="";
                }else if(bt16.getText().equals(aux)){
                     
                    bt16.setText("");
                    
                }
                
                int cont=0;
                int verifica=0;
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                    
                }
            }
            
            
          
       }       // TODO add your handling code here:
    }//GEN-LAST:event_bt15ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        if((!(bt2.getText().equals("")))&&(bt1.getText().equals("")||bt7.getText().equals("")||bt3.getText().equals(""))){
            int cont=0;
            int verifica=0;
          
                aux=bt2.getText();
                bt2.setText("");
            
                if(bt1.getText().equals("")){
                      
                      bt1.setText(aux);
                      test[0]=aux;
                      
                       
                      
                }else if(bt7.getText().equals("")){
                    
                    bt7.setText(aux);
                    test[6]=aux;
                }else if(bt3.getText().equals("")){
                     
                    bt3.setText(aux);
                     test[2]=aux;
                }
                test[1]="";
                
                
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            
            
            
          
       }       //
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
         if((!(bt3.getText().equals("")))&&(bt2.getText().equals("")||bt8.getText().equals("")||bt4.getText().equals(""))){
            int cont=0;
            int verifica=0;
          
                aux=bt3.getText();
                bt3.setText("");
            
                if(bt2.getText().equals("")){
                      
                      bt2.setText(aux);
                      test[1]=aux;
                      
                       
                      
                }else if(bt8.getText().equals("")){
                    
                    bt7.setText(aux);
                    test[6]=aux;
                }else if(bt4.getText().equals("")){
                     
                    bt4.setText(aux);
                     test[3]=aux;
                }
                test[2]="";
                
                
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            
            
            
          
       }     
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
      if((!(bt6.getText().equals("")))&&(bt1.getText().equals("")||bt7.getText().equals("")||bt11.getText().equals(""))){
            int cont=0;
            int verifica=0;
          
                aux=bt6.getText();
                bt6.setText("");
            
                if(bt1.getText().equals("")){
                      
                      bt1.setText(aux);
                      test[0]=aux;
                      
                       
                      
                }else if(bt7.getText().equals("")){
                    
                    bt7.setText(aux);
                    test[6]=aux;
                }else if(bt11.getText().equals("")){
                     
                    bt11.setText(aux);
                     test[10]=aux;
                }
                test[5]="";
                
                
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            
            
            
          
       }       //
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        // TODO add your handling code here:
        if(bt6.getText().equals("")||bt11.getText().equals("")||bt12.getText().equals("")||bt16.getText().equals("")){
            if(chave==false&&!(bt11.getText().equals(""))){
                aux=bt11.getText();
                chave=true;
             }else if(chave==true){
                 bt11.setText(aux);
                 chave=false;
                  test[10]=aux;
                if(bt6.getText().equals(aux)){
                      
                      bt6.setText("");
                      test[5]="";
                      
                }else if(bt12.getText().equals(aux)){
                    
                    bt12.setText("");
                    test[11]="";
                }else if(bt16.getText().equals(aux)){
                     
                    bt16.setText("");
                    
                }
                
                int cont=0;
                int verifica=0;
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            }
            
            
          
       }    
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
        // TODO add your handling code here:
        if(bt11.getText().equals("")||bt12.getText().equals("")||bt16.getText().equals("")||bt13.getText().equals("")||bt7.getText().equals("")){
            if(chave==false&&!(bt12.getText().equals(""))){
                aux=bt12.getText();
                chave=true;
             }else if(chave==true){
                 bt12.setText(aux);
                 chave=false;
                 test[11]=aux;
                if(bt11.getText().equals(aux)){
                      
                      bt11.setText("");
                      test[10]="";
                      
                }else if(bt7.getText().equals(aux)){
                    
                    bt7.setText("");
                    test[6]="";
                }else if(bt16.getText().equals(aux)){
                     
                    bt16.setText("");
                    
                }else if(bt13.getText().equals(aux)){
                     
                    bt13.setText("");
                    test[12]="";
                    
                }
                
                int cont=0;
                int verifica=0;
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            }
            
            
          
       }    
    }//GEN-LAST:event_bt12ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        if((!(bt7.getText().equals("")))&&(bt6.getText().equals("")||bt12.getText().equals("")||bt8.getText().equals("")||bt2.getText().equals(""))){
            int cont=0;
            int verifica=0;
          
                aux=bt7.getText();
                bt7.setText("");
            
                if(bt2.getText().equals("")){
                      
                      bt2.setText(aux);
                      test[1]=aux;
                      
                       
                      
                }else if(bt8.getText().equals("")){
                    
                    bt8.setText(aux);
                    test[7]=aux;
                }else if(bt12.getText().equals("")){
                     
                    bt12.setText(aux);
                     test[11]=aux;
                }else if(bt6.getText().equals("")){
                     
                    bt6.setText(aux);
                     test[5]=aux;
                }
                test[6]="";
                
                
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            
            
            
          
       } 
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here
         if(bt3.getText().equals("")||bt7.getText().equals("")||bt8.getText().equals("")||bt9.getText().equals("")||bt13.getText().equals("")){
            if(chave==false&&!(bt8.getText().equals(""))){
                aux=bt8.getText();
                chave=true;
             }else if(chave==true){
                 bt8.setText(aux);
                 chave=false;
                  test[7]=aux;
                if(bt3.getText().equals(aux)){
                      
                      bt3.setText("");
                      test[2]="";
                      
                }else if(bt7.getText().equals(aux)){
                    
                    bt7.setText("");
                    test[6]="";
                }else if(bt9.getText().equals(aux)){
                     
                    bt9.setText("");
                    test[8]="";
                }else if(bt12.getText().equals(aux)){
                     
                    bt12.setText("");
                    test[13]="";
                    
                }
                
                int cont=0;
                int verifica=0;
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
               if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            }
            
            
          
       }
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt14ActionPerformed
        // TODO add your handling code here:
         if(bt9.getText().equals("")||bt13.getText().equals("")||bt14.getText().equals("")||bt15.getText().equals("")||bt16.getText().equals("")){
            if(chave==false&&!(bt14.getText().equals(""))){
                aux=bt14.getText();
                chave=true;
             }else if(chave==true){
                 bt14.setText(aux);
                 chave=false;
                 test[13]=aux;
                if(bt9.getText().equals(aux)){
                      
                      bt9.setText("");
                      test[8]="";
                      
                }else if(bt13.getText().equals(aux)){
                    
                    bt13.setText("");
                    test[12]="";
                }else if(bt16.getText().equals(aux)){
                     
                    bt16.setText("");
                    
                }else if(bt15.getText().equals(aux)){
                     
                    bt15.setText("");
                    test[14]="";
                    
                }
                
                int cont=0;
                int verifica=0;
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            }
            
            
          
       }
    }//GEN-LAST:event_bt14ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
         if(bt4.getText().equals("")||bt8.getText().equals("")||bt9.getText().equals("")||bt10.getText().equals("")||bt14.getText().equals("")){
            if(chave==false&&!(bt9.getText().equals(""))){
                aux=bt9.getText();
                chave=true;
             }else if(chave==true){
                 bt9.setText(aux);
                 chave=false;
                  test[8]=aux;
                if(bt4.getText().equals(aux)){
                      
                      bt4.setText("");
                      test[3]="";
                      
                }else if(bt8.getText().equals(aux)){
                    
                    bt8.setText("");
                    test[7]="";
                }else if(bt10.getText().equals(aux)){
                     
                    bt10.setText("");
                    test[9]="";
                    
                }else if(bt14.getText().equals(aux)){
                     
                    bt14.setText("");
                    test[13]="";
                    
                }
                
                int cont=0;
                int verifica=0;
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            }
            
            
          
       }
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
             if((!(bt4.getText().equals("")))&&(bt3.getText().equals("")||bt9.getText().equals("")||bt5.getText().equals(""))){
            int cont=0;
            int verifica=0;
          
                aux=bt4.getText();
                bt4.setText("");
            
                if(bt3.getText().equals("")){
                      
                      bt3.setText(aux);
                      test[2]=aux;
                      
                       
                      
                }else if(bt9.getText().equals("")){
                    
                    bt9.setText(aux);
                    test[7]=aux;
                }else if(bt5.getText().equals("")){
                     
                    bt5.setText(aux);
                     test[4]=aux;
                }
                test[3]="";
                
                
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            
            
            
          
       } 
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        if((!(bt5.getText().equals("")))&&(bt4.getText().equals("")||bt10.getText().equals(""))){
         int cont=0;
         int verifica=0;  
         
                aux=bt5.getText();
                bt5.setText("");
                test[4]="";
                if(bt4.getText().equals("")){
                      
                      bt4.setText(aux);
                      test[3]=aux;
                      
                      
                }else if(bt10.getText().equals("")){
                    
                    bt10.setText(aux);
                    test[9]=aux;
                }
                
            
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
              
             
            
                
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            
            
            
          
       }       //
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        // TODO add your handling code here:
      if((!(bt10.getText().equals("")))&&(bt9.getText().equals("")||bt5.getText().equals("")||bt15.getText().equals(""))){
            int cont=0;
            int verifica=0;
          
                aux=bt10.getText();
                bt10.setText("");
            
                if(bt5.getText().equals("")){
                      
                      bt5.setText(aux);
                      test[4]=aux;
                      
                       
                      
                }else if(bt9.getText().equals("")){
                    
                    bt9.setText(aux);
                    test[8]=aux;
                }else if(bt15.getText().equals("")){
                     
                    bt15.setText(aux);
                     test[14]=aux;
                }
                test[9]="";
                
                
                
                //verifica se os blocos, de 1 a 15, estão preenchidos
                for(int j=0;j<15;j++){
                        if(!(test[j].equals(""))){
                            cont++;
                        }
                    }
                
                //verifica se os blocos de 1 a 15 estão em ordem crescente
                if(cont==15){
                    for(int i=0;i<14;i++){
                        
                        if((Integer.valueOf(test[i]))<Integer.valueOf(test[i+1])){
                            verifica++;
                        }
                    }
                }
                
                if(verifica==14){
                    JOptionPane.showMessageDialog(null,"Vitória","",1);
                }
            
            
            
          
       }       //
           
        
    }//GEN-LAST:event_bt10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt13;
    private javax.swing.JButton bt14;
    private javax.swing.JButton bt15;
    private javax.swing.JButton bt16;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
